# Developed by Eng Mouaz M. Al-Shahmeh
name: tqdr_service_provider
description: TQDR Service Provider # Developed by: Eng Mouaz M AlShahmeh

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  provider: ^6.0.0
  whatsapp_unilink: ^2.0.1+1
  blue_thermal_printer: ^1.2.0
  permission_handler: ^8.3.0
  fluttertoast: ^8.0.8
  http: ^0.13.4
  shared_preferences: ^2.0.13
  android_external_storage:
  path_provider:
  pdf:
  printing:
  qr_flutter:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf
